const products=[
{id:'rice-cooker-5l',category:'Home Goods',name:'5L Smart Rice Cooker Lot',discount:'-62%',stock:5200,moq:100,price:18.9,oldPrice:49.8,ship:'Sea 18-28 days',icon:'appliance'},
{id:'bluetooth-earbuds',category:'Electronics',name:'Bluetooth Earbuds Overstock',discount:'-58%',stock:12800,moq:300,price:4.2,oldPrice:9.9,ship:'Air 7-12 days',icon:'audio'},
{id:'beauty-skincare',category:'Beauty',name:'Skincare Gift Set Inventory',discount:'-66%',stock:8600,moq:200,price:3.6,oldPrice:10.5,ship:'Sea 20-32 days',icon:'beauty'},
{id:'cotton-hoodies',category:'Apparel',name:'Cotton Hoodie Mixed Colors',discount:'-54%',stock:3400,moq:120,price:6.8,oldPrice:14.7,ship:'Sea 18-30 days',icon:'apparel'},
{id:'cordless-drill',category:'Tools',name:'Cordless Drill Clearance',discount:'-60%',stock:2100,moq:80,price:15.4,oldPrice:38.5,ship:'Sea 22-35 days',icon:'tool'},
{id:'storage-boxes',category:'Consumer Goods',name:'Foldable Storage Box Lot',discount:'-65%',stock:15000,moq:500,price:1.15,oldPrice:3.3,ship:'Sea 20-30 days',icon:'box'}
];
const icons={
appliance:'<svg viewBox="0 0 120 120" fill="none"><rect x="24" y="18" width="72" height="84" rx="10" stroke-width="6"/><path d="M38 42h44M38 60h44M44 82h32" stroke-width="6" stroke-linecap="round"/><circle cx="78" cy="30" r="4" fill="#0ea5e9"/></svg>',
audio:'<svg viewBox="0 0 120 120" fill="none"><path d="M38 62c0-18 8-34 22-34s22 16 22 34" stroke-width="6" stroke-linecap="round"/><rect x="24" y="58" width="24" height="34" rx="10" stroke-width="6"/><rect x="72" y="58" width="24" height="34" rx="10" stroke-width="6"/><path d="M48 90h24" stroke-width="6" stroke-linecap="round"/></svg>',
beauty:'<svg viewBox="0 0 120 120" fill="none"><rect x="42" y="34" width="36" height="64" rx="8" stroke-width="6"/><path d="M48 34V20h24v14M44 58h32" stroke-width="6" stroke-linecap="round"/><path d="M56 74h8" stroke-width="6" stroke-linecap="round"/></svg>',
apparel:'<svg viewBox="0 0 120 120" fill="none"><path d="M44 24l16 10 16-10 22 18-12 18-10-6v42H44V54l-10 6-12-18 22-18z" stroke-width="6" stroke-linejoin="round"/></svg>',
tool:'<svg viewBox="0 0 120 120" fill="none"><path d="M28 44h44l18 18-12 12-18-18H28V44z" stroke-width="6" stroke-linejoin="round"/><path d="M36 56v34h20V56" stroke-width="6" stroke-linejoin="round"/><path d="M76 43l12-12 8 8-12 12" stroke-width="6" stroke-linecap="round"/></svg>',
box:'<svg viewBox="0 0 120 120" fill="none"><path d="M22 42l38-20 38 20-38 20-38-20z" stroke-width="6" stroke-linejoin="round"/><path d="M22 42v38l38 20 38-20V42M60 62v38" stroke-width="6" stroke-linejoin="round"/></svg>'
};
let activeCategory='All',query='';const quote=new Map();
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:v<10?2:0}).format(v);
const grid=document.querySelector('#product-grid'),drawer=document.querySelector('#quote-drawer'),itemsEl=document.querySelector('#quote-items'),totalEl=document.querySelector('#quote-total'),note=document.querySelector('#form-note');
function renderProducts(){const q=query.trim().toLowerCase();const visible=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)));grid.innerHTML=visible.map(p=>`<article class="product-card"><div class="product-visual" aria-hidden="true"><span class="discount">${p.discount}</span>${icons[p.icon]}</div><div class="card-body"><div class="card-kicker"><span>${p.category}</span><span class="verified">Verified stock</span></div><h3>${p.name}</h3><div class="price-line"><span class="unit-price">${money(p.price)}</span><span class="old-price">${money(p.oldPrice)}</span></div><div class="product-meta"><span>${p.stock.toLocaleString()} units available</span><span>MOQ ${p.moq.toLocaleString()} units</span><span>${p.ship}</span></div><button class="add-button ${quote.has(p.id)?'added':''}" type="button" data-add="${p.id}">${quote.has(p.id)?'Added to quote':'Add to quote'}</button></div></article>`).join('')||'<p class="empty-quote">No matching inventory. Try another category or keyword.</p>'}
function renderQuote(){const items=[...quote.values()];itemsEl.innerHTML=items.length?items.map(p=>`<article class="quote-item"><header><strong>${p.name}</strong><button class="remove-button" type="button" data-remove="${p.id}">Remove</button></header><span>${p.category} - MOQ ${p.moq.toLocaleString()} units</span><strong>${money(p.price*p.moq)}</strong></article>`).join(''):'<div class="empty-quote">No products selected yet.</div>';totalEl.textContent=money(items.reduce((s,p)=>s+p.price*p.moq,0));}
function openQuote(){renderQuote();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')}
function closeQuote(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
function schema(){document.querySelector('#product-schema').textContent=JSON.stringify({'@context':'https://schema.org','@type':'ItemList',itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,item:{'@type':'Product',name:p.name,category:p.category,offers:{'@type':'Offer',priceCurrency:'USD',price:p.price,availability:'https://schema.org/InStock',inventoryLevel:p.stock,seller:{'@type':'Organization',name:'CNSURPR.COM'}}}}))});}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(t=>t.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;renderProducts()}));
document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();query=document.querySelector('#search-input').value;renderProducts();document.querySelector('#deals').scrollIntoView({behavior:'smooth'})});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),rem=e.target.closest('[data-remove]'),open=e.target.closest('[data-open-quote]'),close=e.target.closest('[data-close-quote]');if(add){const p=products.find(x=>x.id===add.dataset.add);quote.has(p.id)?quote.delete(p.id):quote.set(p.id,p);if(quote.has(p.id))openQuote();renderProducts();renderQuote()}if(rem){quote.delete(rem.dataset.remove);renderProducts();renderQuote()}if(open)openQuote();if(close||e.target===drawer)closeQuote()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeQuote()});
document.querySelector('#quote-form').addEventListener('submit',e=>{e.preventDefault();const payload={...Object.fromEntries(new FormData(e.currentTarget)),products:[...quote.keys()],createdAt:new Date().toISOString()};localStorage.setItem('cnsurpr:lastQuoteRequest',JSON.stringify(payload));note.textContent='Quote request saved locally. Backend endpoint can post this payload when connected.'});
schema();renderProducts();renderQuote();
